### ISSUE TITLE
Socks4, Socks5  support

### ISSUE THREAD

**Issue by bawzz234** [nates/ProxyChecker#1]
Hello,

Great work on this. The checking accuracy is perfect.

Could you please also add socks support for both socks5 and socks4? With Go's threading and accuracy, it will be a great addition. 

Best Regards

**Comment by nates** [comment]
I'll look into this. 👍

**Comment by nates** [comment]
I have added SOCKS5 support.

**Comment by bawzz234** [comment]
Thanks for adding socks5 support. It is working perfectly. Btw, you can also add socks4 support using the following package:
https://github.com/h12w/socks

It is recently updated and more improved. You can also update to their socks5 as well. 

Best Regards

**Comment by nates** [comment]
I will do this later today

**Comment by nates** [comment]
Added SOCKS4 support.

**Comment by bawzz234** [comment]
Thanks for adding the socks4 support. Proxies being recognized properly. Golang's accuracy on checking and threading is much proper. The threads you called, is it using goroutines? 

Thanks for the great work. 

Best Regards

**Comment by nates** [comment]
I used WaitGroups
