### ISSUE TITLE
ability to check custom site/url, set timeout and custom in and out file

### ISSUE THREAD

**Issue by bawzz234** [nates/ProxyChecker#2]
Hi, 

The checker is working properly for all protocols. However, I have noticed some working proxies were ignored while checking. It could be because of the site's restriction, or the proxies were distorting. I also found, sometime proxies weren't saved on working.txt file even though logs/verbose was showing there were working proxies. 

- [x] A way to set custom URL would be very useful, (for example, using -URL https://www.google.com) in this way we will also be able to find supported proxies. 

- [x] Another feature is, to set a string from source code to validate the proxies,  because sometime status code: 200 can be from different sites as some proxies may redirect to their access pages or invalid pages etc.  (For example: -URL https://www.google.com -text google)

- [x] Some sites can intentionally delays to load and some sites are generally slow. In this case setting up a custom timeout will surely help. Example: (-timeout 10)

- [x] Having an option to set input and output would very useful as well. For example: (-input test.txt -out result.txt)

So total command may look something like this: `checker.exe -threads 300 -timeout 8 -type socks4 -url "https://github.com/nates/ProxyChecker" -text "title>nates/ProxyChecker"`

Best Regards

**Comment by nates** [comment]
Will work on this later.

**Comment by nates** [comment]
I have added the following flags.

**Comment by bawzz234** [comment]
Thanks for adding these features. I have tested and everything seems to be working perfectly. 

Best Regards
