### ISSUE TITLE
I found a bug

### ISSUE THREAD

**Issue by bawzz234** [nates/ProxyChecker#3]
Hello,

This error is randomly appearing while checking: 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x658bc5]

goroutine 447 [running]:
regexp.(*inputString).context(0xc0018b2e40, 0x0, 0x2)
        c:/go/src/regexp/regexp.go:417 +0x65
regexp.(*Regexp).tryBacktrack(0xc0056c9680, 0xc0018b2dc0, 0x732f80, 0xc0018b2e40, 0x1, 0x0
, 0xa0)
        c:/go/src/regexp/backtrack.go:260 +0x7f9
regexp.(*Regexp).backtrack(0xc0056c9680, 0x0, 0x0, 0x0, 0x0, 0x12, 0x0, 0x0, 0x8d8360, 0x0
, ...)
        c:/go/src/regexp/backtrack.go:353 +0x3af
regexp.(*Regexp).doExecute(0xc0056c9680, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x12, 0x0, 0x0, ...
)
        c:/go/src/regexp/exec.go:535 +0x44d
regexp.(*Regexp).doMatch(...)
        c:/go/src/regexp/exec.go:514
regexp.(*Regexp).MatchString(...)
        c:/go/src/regexp/regexp.go:525
regexp.MatchString(0x6e39ae, 0x2d, 0x0, 0x12, 0x40, 0x38, 0x0)
        c:/go/src/regexp/regexp.go:553 +0xee
main.worker(0x18c, 0xc0004ee0f0, 0xc000088ba0, 0xc000094a40, 0xc000088b80, 0xc000088b90)
        C:/Users/Administrator/Downloads/test/
ProxyChecker-master/src/checker/main.go:71 +0xf9
main.worker(0x18c, 0xc0004ee0f0, 0xc000088ba0, 0xc000094a40, 0xc000088b80, 0xc000088b90)
        C:/Users/Administrator/Downloads/test/
ProxyChecker-master/src/checker/main.go:85 +0x72d
main.worker(0x18c, 0xc0004ee0f0, 0xc000088ba0, 0xc000094a40, 0xc000088b80, 0xc000088b90)
        C:/Users/Administrator/Downloads/test/
ProxyChecker-master/src/checker/main.go:85 +0x72d
main.worker(0x18c, 0xc0004ee0f0, 0xc000088ba0, 0xc000094a40, 0xc000088b80, 0xc000088b90)
        C:/Users/Administrator/Downloads/test/
ProxyChecker-master/src/checker/main.go:85 +0x72d
main.worker(0x18c, 0xc0004ee0f0, 0xc000088ba0, 0xc000094a40, 0xc000088b80, 0xc000088b90)
        C:/Users/Administrator/Downloads/test/
ProxyChecker-master/src/checker/main.go:85 +0x72d
main.worker(0x18c, 0xc0004ee0f0, 0xc000088ba0, 0xc000094a40, 0xc000088b80, 0xc000088b90)
        C:/Users/Administrator/Downloads/test/
ProxyChecker-master/src/checker/main.go:85 +0x72d
main.worker(0x18c, 0xc0004ee0f0, 0xc000088ba0, 0xc000094a40, 0xc000088b80, 0xc000088b90)
        C:/Users/Administrator/Downloads/test/
ProxyChecker-master/src/checker/main.go:85 +0x72d
main.worker(0x18c, 0xc0004ee0f0, 0xc000088ba0, 0xc000094a40, 0xc000088b80, 0xc000088b90)
        C:/Users/Administrator/Downloads/test/
ProxyChecker-master/src/checker/main.go:85 +0x72d
main.worker(0x18c, 0xc0004ee0f0, 0xc000088ba0, 0xc000094a40, 0xc000088b80, 0xc000088b90)
        C:/Users/Administrator/Downloads/test/
ProxyChecker-master/src/checker/main.go:85 +0x72d
main.worker(0x18c, 0xc0004ee0f0, 0xc000088ba0, 0xc000094a40, 0xc000088b80, 0xc000088b90)
        C:/Users/Administrator/Downloads/test/
ProxyChecker-master/src/checker/main.go:85 +0x72d
main.worker(0x18c, 0xc0004ee0f0, 0xc000088ba0, 0xc000094a40, 0xc000088b80, 0xc000088b90)
        C:/Users/Administrator/Downloads/test/
ProxyChecker-master/src/checker/main.go:85 +0x72d
main.worker(0x18c, 0xc0004ee0f0, 0xc000088ba0, 0xc000094a40, 0xc000088b80, 0xc000088b90)
        C:/Users/Administrator/Downloads/test/
ProxyChecker-master/src/checker/main.go:85 +0x72d
main.worker(0x18c, 0xc0004ee0f0, 0xc000088ba0, 0xc000094a40, 0xc000088b80, 0xc000088b90)
        C:/Users/Administrator/Downloads/test/
ProxyChecker-master/src/checker/main.go:85 +0x72d
main.worker(0x18c, 0xc0004ee0f0, 0xc000088ba0, 0xc000094a40, 0xc000088b80, 0xc000088b90)
        C:/Users/Administrator/Downloads/test/
ProxyChecker-master/src/checker/main.go:85 +0x72d
main.worker(0x18c, 0xc0004ee0f0, 0xc000088ba0, 0xc000094a40, 0xc000088b80, 0xc000088b90)
        C:/Users/Administrator/Downloads/test/
ProxyChecker-master/src/checker/main.go:85 +0x72d
main.worker(0x18c, 0xc0004ee0f0, 0xc000088ba0, 0xc000094a40, 0xc000088b80, 0xc000088b90)
        C:/Users/Administrator/Downloads/test/
ProxyChecker-master/src/checker/main.go:85 +0x72d
main.worker(0x18c, 0xc0004ee0f0, 0xc000088ba0, 0xc000094a40, 0xc000088b80, 0xc000088b90)
        C:/Users/Administrator/Downloads/test/
ProxyChecker-master/src/checker/main.go:85 +0x72d
main.worker(0x18c, 0xc0004ee0f0, 0xc000088ba0, 0xc000094a40, 0xc000088b80, 0xc000088b90)
        C:/Users/Administrator/Downloads/test/
ProxyChecker-master/src/checker/main.go:85 +0x72d
main.worker(0x18c, 0xc0004ee0f0, 0xc000088ba0, 0xc000094a40, 0xc000088b80, 0xc000088b90)
        C:/Users/Administrator/Downloads/test/
ProxyChecker-master/src/checker/main.go:85 +0x72d
main.worker(0x18c, 0xc0004ee0f0, 0xc000088ba0, 0xc000094a40, 0xc000088b80, 0xc000088b90)
        C:/Users/Administrator/Downloads/test/
ProxyChecker-master/src/checker/main.go:85 +0x72d
created by main.main
        C:/Users/Administrator/Downloads/test/
ProxyChecker-master/src/checker/main.go:38 +0x39c
```

When this error occurs, working proxies do not save to the output txt. Proxies in the list is none other than IP:PORT format.

Best Regards

**Comment by nates** [comment]
I'm pretty sure it has to do with the RegEx checker, so I will remove it.

**Comment by bawzz234** [comment]
Hello,

that bug was removed but another has appeared. 

`
[145] Error requesting https://www.scribd.com/show_features_promo
[799] Error requesting https://www.scribd.com/show_features_promo
[116] Error requesting https://www.scribd.com/show_features_promo
[461] Error requesting https://www.scribd.com/show_features_promo
panic: runtime error: index out of range [1] with length 1

goroutine 515 [running]:
main.worker(0x1cd, 0xc00067ca70, 0xc00002ebb0, 0xc000012a60, 0xc00002eb90, 0xc00002eba0)
        C:/Users/Administrator/Downloads/test2/
ProxyChecker-master/src/checker/main.go:70 +0x7af
main.worker(0x1cd, 0xc00067ca70, 0xc00002ebb0, 0xc000012a60, 0xc00002eb90, 0xc00002eba0)
        C:/Users/Administrator/Downloads/test2/
ProxyChecker-master/src/checker/main.go:73 +0x6d9
main.worker(0x1cd, 0xc00067ca70, 0xc00002ebb0, 0xc000012a60, 0xc00002eb90, 0xc00002eba0)
        C:/Users/Administrator/Downloads/test2/
ProxyChecker-master/src/checker/main.go:73 +0x6d9
main.worker(0x1cd, 0xc00067ca70, 0xc00002ebb0, 0xc000012a60, 0xc00002eb90, 0xc00002eba0)
        C:/Users/Administrator/Downloads/test2/
ProxyChecker-master/src/checker/main.go:73 +0x6d9
main.worker(0x1cd, 0xc00067ca70, 0xc00002ebb0, 0xc000012a60, 0xc00002eb90, 0xc00002eba0)
        C:/Users/Administrator/Downloads/test2/
ProxyChecker-master/src/checker/main.go:73 +0x6d9
main.worker(0x1cd, 0xc00067ca70, 0xc00002ebb0, 0xc000012a60, 0xc00002eb90, 0xc00002eba0)
        C:/Users/Administrator/Downloads/test2/
ProxyChecker-master/src/checker/main.go:73 +0x6d9
main.worker(0x1cd, 0xc00067ca70, 0xc00002ebb0, 0xc000012a60, 0xc00002eb90, 0xc00002eba0)
        C:/Users/Administrator/Downloads/test2/
ProxyChecker-master/src/checker/main.go:73 +0x6d9
main.worker(0x1cd, 0xc00067ca70, 0xc00002ebb0, 0xc000012a60, 0xc00002eb90, 0xc00002eba0)
        C:/Users/Administrator/Downloads/test2/
ProxyChecker-master/src/checker/main.go:73 +0x6d9
main.worker(0x1cd, 0xc00067ca70, 0xc00002ebb0, 0xc000012a60, 0xc00002eb90, 0xc00002eba0)
        C:/Users/Administrator/Downloads/test2/
ProxyChecker-master/src/checker/main.go:73 +0x6d9
main.worker(0x1cd, 0xc00067ca70, 0xc00002ebb0, 0xc000012a60, 0xc00002eb90, 0xc00002eba0)
        C:/Users/Administrator/Downloads/test2/
ProxyChecker-master/src/checker/main.go:73 +0x6d9
main.worker(0x1cd, 0xc00067ca70, 0xc00002ebb0, 0xc000012a60, 0xc00002eb90, 0xc00002eba0)
        C:/Users/Administrator/Downloads/test2/
ProxyChecker-master/src/checker/main.go:73 +0x6d9
main.worker(0x1cd, 0xc00067ca70, 0xc00002ebb0, 0xc000012a60, 0xc00002eb90, 0xc00002eba0)
        C:/Users/Administrator/Downloads/test2/
ProxyChecker-master/src/checker/main.go:73 +0x6d9
main.worker(0x1cd, 0xc00067ca70, 0xc00002ebb0, 0xc000012a60, 0xc00002eb90, 0xc00002eba0)
        C:/Users/Administrator/Downloads/test2/
ProxyChecker-master/src/checker/main.go:73 +0x6d9
main.worker(0x1cd, 0xc00067ca70, 0xc00002ebb0, 0xc000012a60, 0xc00002eb90, 0xc00002eba0)
        C:/Users/Administrator/Downloads/test2/
ProxyChecker-master/src/checker/main.go:73 +0x6d9
main.worker(0x1cd, 0xc00067ca70, 0xc00002ebb0, 0xc000012a60, 0xc00002eb90, 0xc00002eba0)
        C:/Users/Administrator/Downloads/test2/
ProxyChecker-master/src/checker/main.go:73 +0x6d9
main.worker(0x1cd, 0xc00067ca70, 0xc00002ebb0, 0xc000012a60, 0xc00002eb90, 0xc00002eba0)
        C:/Users/Administrator/Downloads/test2/
ProxyChecker-master/src/checker/main.go:73 +0x6d9
main.worker(0x1cd, 0xc00067ca70, 0xc00002ebb0, 0xc000012a60, 0xc00002eb90, 0xc00002eba0)
        C:/Users/Administrator/Downloads/test2/
ProxyChecker-master/src/checker/main.go:73 +0x6d9
main.worker(0x1cd, 0xc00067ca70, 0xc00002ebb0, 0xc000012a60, 0xc00002eb90, 0xc00002eba0)
        C:/Users/Administrator/Downloads/test2/
ProxyChecker-master/src/checker/main.go:73 +0x6d9
main.worker(0x1cd, 0xc00067ca70, 0xc00002ebb0, 0xc000012a60, 0xc00002eb90, 0xc00002eba0)
        C:/Users/Administrator/Downloads/test2/
ProxyChecker-master/src/checker/main.go:73 +0x6d9
main.worker(0x1cd, 0xc00067ca70, 0xc00002ebb0, 0xc000012a60, 0xc00002eb90, 0xc00002eba0)
        C:/Users/Administrator/Downloads/test2/
ProxyChecker-master/src/checker/main.go:73 +0x6d9
main.worker(0x1cd, 0xc00067ca70, 0xc00002ebb0, 0xc000012a60, 0xc00002eb90, 0xc00002eba0)
        C:/Users/Administrator/Downloads/test2/
ProxyChecker-master/src/checker/main.go:73 +0x6d9
created by main.main
        C:/Users/Administrator/Downloads/test2/
ProxyChecker-master/src/checker/main.go:37 +0x39c
`
This error is also randomly appears like the previous, sometime on first run, and sometime in the middle of checking. 

Best Regards

**Comment by nates** [comment]
I will look into this.

**Comment by nates** [comment]
I could not reproduce this bug, but try the new version out.

**Comment by bawzz234** [comment]
Hello, 

just tested the new version, the bug is still appearing as same before

```
[460] Error requesting https://www.google.com/
[739] Error requesting https://www.google.com/
[104] Working proxy, Speed: 1632ms
[354] Error requesting https://www.google.com/
[666] Error requesting https://www.google.com/
[128] Error requesting https://www.google.com/
[985] Error requesting https://www.google.com/
[592] Error requesting https://www.google.com/
[499] Error requesting https://www.google.com/
[563] Error requesting https://www.google.com/
[397] Error requesting https://www.google.com/
panic: runtime error: index out of range [1] with length 1

goroutine 455 [running]:
main.worker(0x18d, 0xc000189c50, 0xc00002ebb0, 0xc000012a60, 0xc00002eb90, 0xc00002eba0)
        C:/Users/Administrator/Downloads/test/
ProxyChecker-master/src/checker/main.go:70 +0x7a8
main.worker(0x18d, 0xc000189c50, 0xc00002ebb0, 0xc000012a60, 0xc00002eb90, 0xc00002eba0)
        C:/Users/Administrator/Downloads/test/
ProxyChecker-master/src/checker/main.go:73 +0x6cd
main.worker(0x18d, 0xc000189c50, 0xc00002ebb0, 0xc000012a60, 0xc00002eb90, 0xc00002eba0)
        C:/Users/Administrator/Downloads/test/
ProxyChecker-master/src/checker/main.go:73 +0x6cd
main.worker(0x18d, 0xc000189c50, 0xc00002ebb0, 0xc000012a60, 0xc00002eb90, 0xc00002eba0)
        C:/Users/Administrator/Downloads/test/
ProxyChecker-master/src/checker/main.go:73 +0x6cd
main.worker(0x18d, 0xc000189c50, 0xc00002ebb0, 0xc000012a60, 0xc00002eb90, 0xc00002eba0)
        C:/Users/Administrator/Downloads/test/
ProxyChecker-master/src/checker/main.go:73 +0x6cd
main.worker(0x18d, 0xc000189c50, 0xc00002ebb0, 0xc000012a60, 0xc00002eb90, 0xc00002eba0)
        C:/Users/Administrator/Downloads/test/
ProxyChecker-master/src/checker/main.go:73 +0x6cd
main.worker(0x18d, 0xc000189c50, 0xc00002ebb0, 0xc000012a60, 0xc00002eb90, 0xc00002eba0)
        C:/Users/Administrator/Downloads/test/
ProxyChecker-master/src/checker/main.go:73 +0x6cd
main.worker(0x18d, 0xc000189c50, 0xc00002ebb0, 0xc000012a60, 0xc00002eb90, 0xc00002eba0)
        C:/Users/Administrator/Downloads/test/
ProxyChecker-master/src/checker/main.go:73 +0x6cd
main.worker(0x18d, 0xc000189c50, 0xc00002ebb0, 0xc000012a60, 0xc00002eb90, 0xc00002eba0)
        C:/Users/Administrator/Downloads/test/
ProxyChecker-master/src/checker/main.go:73 +0x6cd
main.worker(0x18d, 0xc000189c50, 0xc00002ebb0, 0xc000012a60, 0xc00002eb90, 0xc00002eba0)
        C:/Users/Administrator/Downloads/test/
ProxyChecker-master/src/checker/main.go:73 +0x6cd
main.worker(0x18d, 0xc000189c50, 0xc00002ebb0, 0xc000012a60, 0xc00002eb90, 0xc00002eba0)
        C:/Users/Administrator/Downloads/test/
ProxyChecker-master/src/checker/main.go:73 +0x6cd
main.worker(0x18d, 0xc000189c50, 0xc00002ebb0, 0xc000012a60, 0xc00002eb90, 0xc00002eba0)
        C:/Users/Administrator/Downloads/test/
ProxyChecker-master/src/checker/main.go:73 +0x6cd
main.worker(0x18d, 0xc000189c50, 0xc00002ebb0, 0xc000012a60, 0xc00002eb90, 0xc00002eba0)
        C:/Users/Administrator/Downloads/test/
ProxyChecker-master/src/checker/main.go:73 +0x6cd
main.worker(0x18d, 0xc000189c50, 0xc00002ebb0, 0xc000012a60, 0xc00002eb90, 0xc00002eba0)
        C:/Users/Administrator/Downloads/test/
ProxyChecker-master/src/checker/main.go:73 +0x6cd
main.worker(0x18d, 0xc000189c50, 0xc00002ebb0, 0xc000012a60, 0xc00002eb90, 0xc00002eba0)
        C:/Users/Administrator/Downloads/test/
ProxyChecker-master/src/checker/main.go:73 +0x6cd
main.worker(0x18d, 0xc000189c50, 0xc00002ebb0, 0xc000012a60, 0xc00002eb90, 0xc00002eba0)
        C:/Users/Administrator/Downloads/test/
ProxyChecker-master/src/checker/main.go:73 +0x6cd
main.worker(0x18d, 0xc000189c50, 0xc00002ebb0, 0xc000012a60, 0xc00002eb90, 0xc00002eba0)
        C:/Users/Administrator/Downloads/test/
ProxyChecker-master/src/checker/main.go:73 +0x6cd
main.worker(0x18d, 0xc000189c50, 0xc00002ebb0, 0xc000012a60, 0xc00002eb90, 0xc00002eba0)
        C:/Users/Administrator/Downloads/test/
ProxyChecker-master/src/checker/main.go:73 +0x6cd
main.worker(0x18d, 0xc000189c50, 0xc00002ebb0, 0xc000012a60, 0xc00002eb90, 0xc00002eba0)
        C:/Users/Administrator/Downloads/test/
ProxyChecker-master/src/checker/main.go:73 +0x6cd
main.worker(0x18d, 0xc000189c50, 0xc00002ebb0, 0xc000012a60, 0xc00002eb90, 0xc00002eba0)
        C:/Users/Administrator/Downloads/test/
ProxyChecker-master/src/checker/main.go:73 +0x6cd
main.worker(0x18d, 0xc000189c50, 0xc00002ebb0, 0xc000012a60, 0xc00002eb90, 0xc00002eba0)
        C:/Users/Administrator/Downloads/test/
ProxyChecker-master/src/checker/main.go:73 +0x6cd
main.worker(0x18d, 0xc000189c50, 0xc00002ebb0, 0xc000012a60, 0xc00002eb90, 0xc00002eba0)
        C:/Users/Administrator/Downloads/test/
ProxyChecker-master/src/checker/main.go:73 +0x6cd
main.worker(0x18d, 0xc000189c50, 0xc00002ebb0, 0xc000012a60, 0xc00002eb90, 0xc00002eba0)
        C:/Users/Administrator/Downloads/test/
ProxyChecker-master/src/checker/main.go:73 +0x6cd
main.worker(0x18d, 0xc000189c50, 0xc00002ebb0, 0xc000012a60, 0xc00002eb90, 0xc00002eba0)
        C:/Users/Administrator/Downloads/test/
ProxyChecker-master/src/checker/main.go:73 +0x6cd
main.worker(0x18d, 0xc000189c50, 0xc00002ebb0, 0xc000012a60, 0xc00002eb90, 0xc00002eba0)
        C:/Users/Administrator/Downloads/test/
ProxyChecker-master/src/checker/main.go:73 +0x6cd
created by main.main
        C:/Users/Administrator/Downloads/test/
ProxyChecker-master/src/checker/main.go:37 +0x39c

```

I have noticed, when a small list of proxies being checked, this bug doesn't appear at all.  If the list contains more than thousands of proxies, the error shows up at first run or randomly in the middle of checking. So I checked with a big list and this error is always showing up instantly. After multiple retries it tests the proxies but gives the error in the middle of checking. I am sending you the proxy list in attached. 

[proxies.txt](https://github.com/nates/ProxyChecker/files/5326457/proxies.txt)

Best Regards

**Comment by nates** [comment]
I have fixed the issue.

**Comment by bawzz234** [comment]
Thanks for fixing the bug. I have tried big lists and none of the errors have shown on all protocols. I have noticed improvement on speed as well.  

Best Regards
