### ISSUE TITLE
Check all proxy types together (HTTPS, Socks4, Socks5) and save working proxies by the protocols

### ISSUE THREAD

**Issue by bawzz234** [nates/ProxyChecker#4]
Hello,

Thanks again for the great work on this proxychecker and for adding the requested features. I didn't encounter any bugs whatsoever and the checker is working perfectly. 

- [x] Check all proxy types together (HTTPS, Socks4, Socks5)
This feature can be very useful when all type of proxies are mixed in a file. To be able to check all type of proxies together 
(example): -types=socks4,socks5,https. when this feature is selected, output list can be set by their types. (Socks4.txt, Socks5.txt, HTTPS.txt) by default. So if multiple working proxies found from different types, they will be saved by their protocols. 

- [x] New flag, -notext
with this function enabled, if the proxy visit the site and find the string from -notext, it will count as bad proxy. It can be very useful to check anonymity. 

For example, urls like these shows IP only
https://httpbin.org/ip
https://api.ipify.org
https://api.myip.com/

So, if my ip is 1.1.1.1 and if I check with these URLS and set -notext 1.1.1.1 - it will eliminate transparent proxies. This way we can check for elite and anonymous proxies. 

- [x] A program request - ProxyScraper
If it is possible to create a scraper using Golang to scrape proxies from list of urls. After finish scraping, it can give results to output txt files of scraped proxies and working urls with the amount of proxies found. 
Examples:
proxies.txt - the list of scraped proxies (without the duplicates if possible)
GoodURLs - URLs with amount of proxies found (https://github.com/clarketm/proxy-list/blob/master/proxy-list-raw.txt    400)

Best Regards

**Comment by nates** [comment]
I'll either work on this tomorrow or the day after. 👍

**Comment by nates** [comment]
I have added the notext flag and check multiple proxy types together feature.

**Comment by nates** [comment]
I'm going to close this issue, I will create the ProxyScraper program later.

**Comment by bawzz234** [comment]
Hello,

Thanks for adding those features. I tested a proxy file containing all types of proxies together, and checked the protocols separately to compare with all types together. The result was accurate and the result amount was almost same. using IP as -notext is working beautifully and transparent proxies now sorted out. 

Thanks for the great work. Can't wait for the ProxyScraper program.  :)
 
Best Regards

**Comment by nates** [comment]
Created the proxy scraper program, https://github.com/nates/ProxyScraper
