### ISSUE TITLE
Static Binaries

### ISSUE THREAD

**Issue by chromer030** [nates/ProxyChecker#5]
Please provide static binaries ...

**Comment by nates** [comment]
Could you provide more info on this? I've never heard of static binaries.

**Comment by chromer030** [comment]
Excuse me , i mean static builds.

https://en.wikipedia.org/wiki/Static_build

**Comment by nates** [comment]
I have added the release.

**Comment by chromer030** [comment]
please add Linux binary too

**Comment by nates** [comment]
I have added the Linux version in the new release.
